var ex_lib = [
  (ex_1 = {
    name: "Australian Pull Ups",
    goal: 1,
    group: 1,
    level: 1,
    image: "/ex-resources/ex-images/push-ups.png",
    video: "/ex-resources/ex-videos/push-ups.mp4",
    rep: 12,
    rest: 60,
  }),
  (ex_2 = {
    name: "Pull Ups",
    goal: 1,
    group: 1,
    level: 2,
    image: "/ex-resources/ex-images/push-ups.png",
    video: "/ex-resources/ex-videos/push-ups.mp4",
    rep: 12,
    rest: 60,
  }),
  (ex_3 = {
    name: "One Arm Pull Ups",
    goal: 1,
    group: 1,
    level: 3,
    image: "/ex-resources/ex-images/push-ups.png",
    video: "/ex-resources/ex-videos/push-ups.mp4",
    rep: 12,
    rest: 60,
  }),
  (ex_4 = {
    name: "Negative Chin Ups",
    goal: 1,
    group: 2,
    level: 1,
    image: "/ex-resources/ex-images/push-ups.png",
    video: "/ex-resources/ex-videos/push-ups.mp4",
    rep: 12,
    rest: 60,
  }),
  (ex_5 = {
    name: "Bar Curls",
    goal: 1,
    group: 2,
    level: 2,
    image: "/ex-resources/ex-images/push-ups.png",
    video: "/ex-resources/ex-videos/push-ups.mp4",
    rep: 12,
    rest: 60,
  }),
  (ex_6 = {
    name: "One Arm Biceps Curls",
    goal: 1,
    group: 2,
    level: 3,
    image: "/ex-resources/ex-images/push-ups.png",
    video: "/ex-resources/ex-videos/push-ups.mp4",
    rep: 12,
    rest: 60,
  }),
  (ex_7 = {
    name: "Incline Push Ups",
    goal: 1,
    group: 3,
    level: 1,
    image: "/ex-resources/ex-images/push-ups.png",
    video: "/ex-resources/ex-videos/push-ups.mp4",
    rep: 12,
    rest: 60,
  }),
  (ex_8 = {
    name: "Push Ups",
    goal: 1,
    group: 3,
    level: 2,
    image: "/ex-resources/ex-images/push-ups.png",
    video: "/ex-resources/ex-videos/push-ups.mp4",
    rep: 12,
    rest: 60,
  }),
  (ex_9 = {
    name: "Decline Push Ups",
    goal: 1,
    group: 3,
    level: 3,
    image: "/ex-resources/ex-images/push-ups.png",
    video: "/ex-resources/ex-videos/push-ups.mp4",
    rep: 12,
    rest: 60,
  }),
  (ex_10 = {
    name: "Knee Tricep Extensions",
    goal: 1,
    group: 4,
    level: 1,
    image: "/ex-resources/ex-images/push-ups.png",
    video: "/ex-resources/ex-videos/push-ups.mp4",
    rep: 12,
    rest: 60,
  }),
  (ex_11 = {
    name: "Tricep Extensions",
    goal: 1,
    group: 4,
    level: 2,
    image: "/ex-resources/ex-images/push-ups.png",
    video: "/ex-resources/ex-videos/push-ups.mp4",
    rep: 12,
    rest: 60,
  }),
  (ex_12 = {
    name: "Cross Tricep Extensions",
    goal: 1,
    group: 4,
    level: 3,
    image: "/ex-resources/ex-images/push-ups.png",
    video: "/ex-resources/ex-videos/push-ups.mp4",
    rep: 12,
    rest: 60,
  }),
  (ex_13 = {
    name: "Pike Push Ups",
    goal: 1,
    group: 5,
    level: 1,
    image: "/ex-resources/ex-images/push-ups.png",
    video: "/ex-resources/ex-videos/push-ups.mp4",
    rep: 12,
    rest: 60,
  }),
  (ex_14 = {
    name: "Elevated Pike Push Ups",
    goal: 1,
    group: 5,
    level: 2,
    image: "/ex-resources/ex-images/push-ups.png",
    video: "/ex-resources/ex-videos/push-ups.mp4",
    rep: 12,
    rest: 60,
  }),
  (ex_15 = {
    name: "Handstand Push Ups",
    goal: 1,
    group: 5,
    level: 3,
    image: "/ex-resources/ex-images/push-ups.png",
    video: "/ex-resources/ex-videos/push-ups.mp4",
    rep: 12,
    rest: 60,
  }),
  (ex_16 = {
    name: "Squats",
    goal: 1,
    group: 6,
    level: 1,
    image: "/ex-resources/ex-images/push-ups.png",
    video: "/ex-resources/ex-videos/push-ups.mp4",
    rep: 12,
    rest: 60,
  }),
  (ex_17 = {
    name: "Jump Squats",
    goal: 1,
    group: 6,
    level: 2,
    image: "/ex-resources/ex-images/push-ups.png",
    video: "/ex-resources/ex-videos/push-ups.mp4",
    rep: 12,
    rest: 60,
  }),
  (ex_18 = {
    name: "Pistol Squats",
    goal: 1,
    group: 6,
    level: 3,
    image: "/ex-resources/ex-images/push-ups.png",
    video: "/ex-resources/ex-videos/push-ups.mp4",
    rep: 12,
    rest: 60,
  }),
  (ex_19 = {
    name: "Knee Raises",
    goal: 1,
    group: 7,
    level: 1,
    image: "/ex-resources/ex-images/push-ups.png",
    video: "/ex-resources/ex-videos/push-ups.mp4",
    rep: 12,
    rest: 60,
  }),
  (ex_20 = {
    name: "Leg Raises",
    goal: 1,
    group: 7,
    level: 2,
    image: "/ex-resources/ex-images/push-ups.png",
    video: "/ex-resources/ex-videos/push-ups.mp4",
    rep: 12,
    rest: 60,
  }),
  (ex_21 = {
    name: "Toes To Bar",
    goal: 1,
    group: 7,
    level: 3,
    image: "/ex-resources/ex-images/push-ups.png",
    video: "/ex-resources/ex-videos/push-ups.mp4",
    rep: 12,
    rest: 60,
  }),
  (ex_22 = {
    name: "Jumping Jacks",
    goal: 2,
    group: "none",
    level: "none",
    image: "/ex-resources/ex-images/push-ups.png",
    video: "/ex-resources/ex-videos/push-ups.mp4",
    rep: 45,
    rest: 15,
  }),
  (ex_23 = {
    name: "Mountain Climbers",
    goal: 2,
    group: "none",
    level: "none",
    image: "/ex-resources/ex-images/push-ups.png",
    video: "/ex-resources/ex-videos/push-ups.mp4",
    rep: 45,
    rest: 15,
  }),
  (ex_24 = {
    name: "Jump Squats",
    goal: 2,
    group: "none",
    level: "none",
    image: "/ex-resources/ex-images/push-ups.png",
    video: "/ex-resources/ex-videos/push-ups.mp4",
    rep: 45,
    rest: 15,
  }),
  (ex_25 = {
    name: "Bicycles",
    goal: 2,
    group: "none",
    level: "none",
    image: "/ex-resources/ex-images/push-ups.png",
    video: "/ex-resources/ex-videos/push-ups.mp4",
    rep: 45,
    rest: 15,
  }),
  (ex_26 = {
    name: "Jumping Rope",
    goal: 2,
    group: "none",
    level: "none",
    image: "/ex-resources/ex-images/push-ups.png",
    video: "/ex-resources/ex-videos/push-ups.mp4",
    rep: 45,
    rest: 15,
  }),
];
